# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aish < Formula
  desc "AI-powered shell assistant"
  homepage "https://github.com/vklimontovich/aish"
  version "0.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vklimontovich/aish/releases/download/v0.5.6/aish_0.5.6_darwin_amd64.tar.gz"
      sha256 "c808e2b4b1514ddef5d98b5fab9a0cccdd47205789cbf620feb8e1a07418d95b"

      def install
        bin.install "aish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vklimontovich/aish/releases/download/v0.5.6/aish_0.5.6_darwin_arm64.tar.gz"
      sha256 "61927520249694cb1345cecc867593ff99ca49e0c936fa26b729969b89bc432d"

      def install
        bin.install "aish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vklimontovich/aish/releases/download/v0.5.6/aish_0.5.6_linux_amd64.tar.gz"
        sha256 "7f614460d731e25dac071fa3c6f167e42c75d4d83adaeb7d898213a3a605e19f"

        def install
          bin.install "aish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vklimontovich/aish/releases/download/v0.5.6/aish_0.5.6_linux_arm64.tar.gz"
        sha256 "87524efea29bad7d8b51b5b97ad23c04525e03740d1db051d14d94cd5ef028dd"

        def install
          bin.install "aish"
        end
      end
    end
  end
end
